spring:
  application:
    name: maia-jdbi-crud

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

server:
  port: 8080

aws:
  region: ${AWS-REGION:us-east-1}
  sns:
    topic:
      user-event-arn: ${AWS-TOPIC-USER:user-events}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      jvm: true


logging:
  level:
    root: INFO
    org.springframework: INFO
    org.jdbi.v3: DEBUG
