spring:
  application:
    name: maia-jdbi-crud

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

server:
  port: 8080

aws:
  region: ${AWS_REGION}
  topic:
    arn:
      user: arn:aws:sns:us-east-1:426300336245:user-events

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      jvm: true


logging:
  level:
    root: INFO
    org.springframework: INFO
    org.jdbi.v3: DEBUG
