version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=jdbidb
      - MYSQL_USER=maia
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./volume_mysql:/var/lib/mysql
   